name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install dependencies
      run: |
        go get -v -t -d ./...
        go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Make test script executable
      run: chmod +x test_improvements.sh

    - name: Run comprehensive test suite
      run: ./test_improvements.sh
